If NULL_IF list is empty fix it with brackets
chanzuckerberg/terraform-provider-snowflake pull request #264
Opened 2020-10-02 15:50 UTC by funes79

## Test Plan

* [ ] acceptance tests

* [ x] …

## References

* This fix should avoid getting an SQL error when a stage has defined a NULL_IF = [] file format property. The provider now does not run `NULL_IF = []` but it executes `NULL_IF = ()`

2020-10-02 15:53 UTC, funes79 commented
Fixes https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/254

2020-10-06 22:56 UTC, ryanking requested changes

2020-10-06 22:56 UTC, ryanking requested changes
Also, can we get a test for this?

2020-10-07 16:45 UTC, ryanking approved these changes

2020-10-07 16:46 UTC, merged