add external table grant in
chanzuckerberg/terraform-provider-snowflake pull request #310
Opened 2020-11-23 03:07 UTC by fevin86

This introduce external table grant.

2020-12-01 20:09 UTC, ryanking requested changes
Also

* `go fmt` needs to be run.
* `main` has been upgraded to use the provider sdk v2, this will need to be updated as well

2020-12-02 01:07 UTC, fevin86 commented on pkg/resources/external_table_grant.go
> +	}
Thanks for picking it up. I actually just did a copy/paste from the table grant with necessary change. I will clean this up.

2020-12-02 01:07 UTC, fevin86 commented on pkg/resources/external_table_grant.go
> +	}
same as above comment :)

2020-12-08 01:52 UTC, etsheks commented
@ryanking can you please have another look at this PR?

2020-12-08 01:54 UTC, fevin86 commented
@ryanking can you please have another look at this PR?

2020-12-16 19:47 UTC, alldoami commented
@fevin86 could you resolve the conflicts?

2020-12-23 05:57 UTC, fevin86 commented
This can be closed due to another pull request merged.

2020-12-23 05:57 UTC, closed without merging