Add cloud integration outputs azure_consent_url and azure_multi_tenant_app_name
chanzuckerberg/terraform-provider-snowflake pull request #454
Opened 2021-02-17 10:00 UTC by ChineduUzoka

Add azure_consent_url and azure_multi_tenant_app_name as outputs for storage integration resource
## Test Plan
- [x] acceptance tests
- [x] unit test

## References
* https://docs.snowflake.com/en/user-guide/data-load-snowpipe-auto-azure.html#step-2-grant-snowflake-access-to-the-storage-locations

2021-02-18 20:01 UTC, ryanking requested changes

2021-02-18 20:01 UTC, ryanking commented on pkg/resources/storage_integration.go
> +		Description: "",
Please add a description.

2021-02-18 22:36 UTC, ChineduUzoka commented on pkg/resources/storage_integration.go
> +		Description: "",
Oh shoot - ill do that ASAP :-)

2021-02-21 13:06 UTC, ChineduUzoka commented on pkg/resources/storage_integration.go
> +		Description: "",
I believe i have resolved the issue :-)

2021-02-22 13:47 UTC, ChineduUzoka commented
Any chance i can get this PR merged

2021-02-26 17:50 UTC, ryanking commented
@ChineduUzoka sure thing, next time if you click the "re-request review" button next to the reviewer's name we will see it sooner and take a look

2021-02-26 17:51 UTC, ryanking approved these changes

2021-02-26 17:51 UTC, ryanking commented
/okt-to-test sha=60bb02e

2021-02-26 21:58 UTC, alldoami commented
/ok-to-test sha=04f609f

2021-02-26 21:59 UTC, alldoami commented
/ok-to-test sha=1bc32aa

2021-02-26 22:11 UTC, merged