warehouse_grant: update warehouse grants in-place instead of recreating
chanzuckerberg/terraform-provider-snowflake pull request #478
Opened 2021-03-03 10:47 UTC by igungor

Related to #469
Updates #137

2021-03-03 18:27 UTC, alldoami commented
/ok-to-test sha=31c2162

2021-03-04 19:02 UTC, alldoami requested changes
Could you also write a test for Update here? Same goes for the other resources you opened a PR for 😄 thank you!

2021-03-09 11:36 UTC, igungor commented
> Could you also write a test for Update here? Same goes for the other resources you opened a PR for 😄 thank you!

Could you point me to any `update grant` test or give a hint to how to write update grant test, I'd gladly contribute tests too.

2021-03-12 22:39 UTC, alldoami commented
@igungor here 😄  https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/warehouse_grant_test.go

2021-03-15 10:28 UTC, igungor commented
> @igungor here 😄 https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/warehouse_grant_test.go

I know where to put the tests, I was expecting a sample resource update-grant test :)

2021-03-16 22:27 UTC, alldoami commented
@igungor ah sorry, we don't have any example tests right now, would you need help writing them?

2021-03-16 23:58 UTC, alldoami commented on pkg/resources/warehouse_grant.go
> +	); err != nil {
NIT: To follow convention in this file, could you make this `if` separate from the `err` declaration? Same as the ones below.

2021-03-17 18:48 UTC, alldoami approved these changes

2021-03-17 18:48 UTC, alldoami commented
/ok-to-test sha=020a98d

2021-03-17 18:49 UTC, alldoami commented
/ok-to-test sha=b6582a5

2021-03-17 18:57 UTC, merged