[hotfix] Adding missing property to storage integration schema
chanzuckerberg/terraform-provider-snowflake pull request #488
Opened 2021-03-09 09:43 UTC by Sh1n

## Test Plan

* [ ] make test
* [ ] provider used in a GCP live project

2021-03-12 22:48 UTC, alldoami requested changes
Hi! Thanks for the work @Sh1n ! Could you separate this into 2 PRs? One for the `storage_gcp_service_account` and the other for the notification integration?

2021-03-19 17:13 UTC, alldoami requested changes
Run `make docs` 😄

2021-03-19 17:32 UTC, alldoami requested changes
Rename PR to reflect your changes 😄

2021-03-19 17:32 UTC, alldoami commented on pkg/resources/notification_integration.go
> +			if err = d.Set("azure_consent_url", v.(string)); err != nil {
you forgot to put `azure_consent_url` and `azure_multi_tenant_app_name` in the `notificationIntegrationSchema`

2021-03-29 18:46 UTC, alldoami commented
@Sh1n please take a look at my comments.

2021-07-22 23:37 UTC, richardo-ps commented
Anything we can do to help get this merged?

2021-11-29 20:08 UTC, closed without merging